FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04 as base


RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    vim \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code
RUN cd /code && /root/.local/bin/uv venv --python 3.12 --seed --managed-python
RUN cd /code && /root/.local/bin/uv pip install vllm --torch-backend=auto
